wordpress_env_defaults:
  database_host: localhost
  database_name: "{{ site | underscore }}_{{ env }}"
  database_user: "{{ site | underscore }}"
  disable_wp_cron: true
  app_env: "{{ env }}"
  app_url: "{{ project.ssl.enabled | default(false) | ternary('https', 'http') }}://{{ project.site_hosts | map(attribute='canonical') | first }}"
  wp_url: "{{ project.ssl.enabled | default(false) | ternary('https', 'http') }}://{{ project.site_hosts | map(attribute='canonical') | first }}/cms"
  domain_current_site: "{{ project.site_hosts | map(attribute='canonical') | first }}"
  git_sha: "{{ git_clone.after }}"
  release_version: "{{ deploy_helper.new_release }}"

site_env: "{{ wordpress_env_defaults | combine(vault_wordpress_env_defaults | default({}), project.env | default({}), vault_wordpress_sites[site].env) }}"
