---
- name: Pull {{ site }} database from {{ env }} to local
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"

  vars:
    project_root: "{{ www_root }}/{{ site }}"
    project_web_dir: "{{ project_root }}/current"
    host: "{{ env }}_host"
    from_host: "{{ hostvars[host] }}"
    url_from: "{{ from_host.wordpress_sites[site].site_hosts.0.canonical }}"
    url_to: "{{ hostvars.local_host.wordpress_sites[site].site_hosts.0.canonical }}"
    local_bedrock_dir: "{{ hostvars.local_host.wordpress_sites[site].local_path }}"
    dump_file: "{{ site | regex_replace('\\.+', '_') }}_db_dump.sql.gz"
    current_date_and_time: "{{ ansible_date_time.date | regex_replace('\\-+', '_') }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}"
    backup_file: "{{ site | regex_replace('\\.+', '_') }}_local_{{ current_date_and_time }}.sql.gz"

  tasks:
  - name: Abort if environment variable is equal to local
    fail:
      msg: "ERROR: local is not a valid environment for this mode (you can't pull from local to local)."
    when: env == "local"

  - name: Check if {{ site }} folder exists
    delegate_to: local_host
    stat:
      path: "{{ project_root }}"
    register: result

  - name: Abort if {{ site }} folder doesn't exist
    fail:
      msg: "ERROR: {{ site }} is not a valid site name ({{ site }} folder does not exist)."
    when: result.stat.exists is defined and result.stat.exists == false or result.stat.isdir is defined and result.stat.isdir == false

  - block:
    - name: Create database_backup directory if it doesn't exist
      delegate_to: local_host
      file:
        path: "{{ project_web_dir }}/database_backup"
        state: directory
        mode: 0755

    - name: Create database dump on {{ env }}
      shell: wp db export --allow-root - | gzip > {{ dump_file }}
      args:
        chdir: "{{ project_web_dir }}"

    - name: Pull database dump from {{ env }} to local
      fetch:
        src: "{{ project_web_dir }}/{{ dump_file }}"
        dest: "{{ local_bedrock_dir }}/"
        flat: yes

    - name: Delete database dump from {{ env }}
      shell: rm -f {{ dump_file }}
      args:
        chdir: "{{ project_web_dir }}"
        warn: false

    - name: Export local database before importing dump (backup)
      delegate_to: local_host
      shell: wp db export - | gzip > database_backup/{{ backup_file }}
      args:
        chdir: "{{ project_web_dir }}"

    - name: Import database dump on local
      delegate_to: local_host
      shell: gzip -c -d {{ dump_file }} | wp db import -
      args:
        chdir: "{{ project_web_dir }}"

    - name: Delete database dump from local
      delegate_to: local_host
      shell: rm -f {{ dump_file }}
      args:
        chdir: "{{ project_web_dir }}"
        warn: false

    - name: Search for {{ url_from }} and replace with {{ url_to }} on local
      delegate_to: local_host
      command: wp search-replace '//{{ url_from }}' '//{{ url_to }}' --allow-root --all-tables
      args:
        chdir: "{{ project_web_dir }}"
      tags: ['search-replace']
    when: result.stat.exists is defined and result.stat.exists and result.stat.isdir is defined and result.stat.isdir
